### ISSUE TITLE
Code does not work

### ISSUE THREAD

**Issue by navjeetc** [samselikoff/mirage-vue-demo#1]
I had to update package.json to mirage server v 0.1.9 but the app does not load. I get the following errror:

`
Navigated to http://localhost:8080/
log.js?1afd:24 [HMR] Waiting for update signal from WDS...
App.vue?234e:21 Uncaught TypeError: _miragejs_server__WEBPACK_IMPORTED_MODULE_1___default.a is not a constructor
    at eval (App.vue?234e:21)
    at Module../node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/App.vue?vue&type=script&lang=js& (app.js:1138)
    at __webpack_require__ (app.js:724)
    at fn (app.js:101)
    at eval (App.vue?f5eb:1)
    at Module../src/App.vue?vue&type=script&lang=js& (app.js:2340)
    at __webpack_require__ (app.js:724)
    at fn (app.js:101)
    at eval (App.vue?180a:1)
    at Module../src/App.vue (app.js:2328)
(anonymous) @ App.vue?234e:21
./node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/App.vue?vue&type=script&lang=js& @ app.js:1138
__webpack_require__ @ app.js:724
fn @ app.js:101
(anonymous) @ App.vue?f5eb:1
./src/App.vue?vue&type=script&lang=js& @ app.js:2340
__webpack_require__ @ app.js:724
fn @ app.js:101
(anonymous) @ App.vue?180a:1
./src/App.vue @ app.js:2328
__webpack_require__ @ app.js:724
fn @ app.js:101
(anonymous) @ main.js:11
./src/main.js @ app.js:2376
__webpack_require__ @ app.js:724
fn @ app.js:101
0 @ app.js:2389
__webpack_require__ @ app.js:724
(anonymous) @ app.js:791
(anonymous) @ app.js:794
vue.runtime.esm.js?2b0e:8398 You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
main.js:42 in Startnull
prompt.js:1 Uncaught SyntaxError: Identifier 'originalPrompt' has already been declared
    at prompt.js:1
`

**Comment by samselikoff** [comment]
@navjeetc whoops – sorry I didn't see this! The demo has since moved to https://github.com/miragejs/vue-demo
